stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-with-registers-base'
    encoder_input_size: 224
    encoder_params:
      dinov2_path: 'facebook/dinov2-with-registers-base'
      normalize: true
    decoder_config_path: 'configs/decoder/ViTXL'
    noise_tau: 0.8
    reshape_to_2d: true

training:
  epochs: 1                    # Changed: 3 -> 1 epoch for quick testing
  ema_decay: 0.9978
  batch_size: 2                # Changed: 8 -> 2 (smaller batch for faster iteration)
  num_workers: 2               # Changed: 8 -> 2 (less CPU overhead)
  clip_grad: 0.0
  log_interval: 10             # Changed: 100 -> 10 (more frequent logging)
  checkpoint_interval: 100     # Changed: 5000 -> 100 (save checkpoints more often)
  sample_interval: 50          # Changed: 0 -> 50 (generate samples during training)
  optimizer:
    lr: 2.0e-4
    betas: [0.5, 0.9]
    weight_decay: 0.0
  scheduler:
    type: cosine
    warmup_epochs: 0           # Changed: 1 -> 0 (no warmup for short runs)
    decay_end_epoch: 1         # Changed: 16 -> 1 (match total epochs)
    base_lr: 2.0e-4
    final_lr: 2.0e-5

gan:
  disc:
    arch:
      dino_ckpt_path: 'models/discs/dino_vit_small_patch8_224.pth'
      ks: 9
      norm_type: 'bn'
      using_spec_norm: true
      recipe: 'S_8'
    optimizer:
      lr: 2.0e-4
      betas: [0.5, 0.9]
      weight_decay: 0.0
    scheduler:
      type: cosine
      warmup_epochs: 0         # Changed: 1 -> 0
      decay_end_epoch: 1       # Changed: 16 -> 1
      base_lr: 2.0e-4
      final_lr: 2.0e-5
    augment:
      prob: 1.0
      cutout: 0.0
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: 0.75
    perceptual_weight: 1.0
    disc_start: 0              # Changed: 8 -> 0 (start discriminator immediately)
    disc_upd_start: 0          # Changed: 6 -> 0 (start discriminator updates immediately)
    lpips_start: 0
    max_d_weight: 10000.0
    disc_updates: 1